# http://www.github.com/oomushi/jquery.collapse.js
# generated by js2coffee 2.0.0 - http://js2.coffee
(($) ->
  $.fn.extend collapse: (customOptions) ->
    if typeof customOptions is 'string'
      switch customOptions
        when 'destroy'
          return @each(->
            $(this).children('.collapsed,.collapsible').removeClass('collapsible').removeClass('collapsed').children('legend').unbind('click.collapse').siblings('.collapse-hidden').removeClass('collapse-hidden').show()
            return
          )
    else
      options = 
        animation: 'slow'
        start: 'first'
        create: (event, element) ->
        beforeClick: (event, element) ->
        afterClick: (event, element) ->
      $.extend options, customOptions
      return @each(->
        $(this).children('fieldset').children('legend').not('.collapsed,.collapsible').bind('click.collapse', (e) ->
          $(this).trigger 'collapsebeforeclick', $(this).parent('.collapsible')
          $(this).siblings().toggleClass('collapse-hidden').slideToggle options.animation
          $(this).parent().toggleClass 'collapsed'
          $(this).trigger 'collapseafterclick', $(this).parent('.collapsible')
          return
        ).parent().addClass 'collapsible'
        switch options.start
          when 'close'
            $(this).find('legend').click()
          when 'first'
            $(this).find('legend').each (index) ->
              if index > 0
                $(this).click()
              return
        $(this).on 'collapsecreate', options.create
        $(this).on 'collapsebeforeclick', options.beforeClick
        $(this).on 'collapseafterclick', options.afterClick
        $(this).trigger 'collapsecreate', $(this)
        return
      )
    return
  return
) jQuery
