# http://www.github.com/oomushi/jquery.collapse.js
# generated by js2coffee 2.0.0 - http://js2.coffee
(($) ->
  $.fn.extend collapse: (customOptions) ->
    if typeof customOptions is 'string'
      switch customOptions
        when 'destroy'
          return @each(->
            $(this).find('legend').unbind 'click.collapse'
            $(this).parent().find('.collapsed,.collapsible').removeClass('collapsible').removeClass 'collapsed'
            $(this).children().not('legend').not('[type="radio"]').show()
            return
          )
    else
      options = 
        animation: 'slow'
        start: 'first'
        create: (event, element) ->
        beforeClick: (event, element) ->
        afterClick: (event, element) ->
      $.extend options, customOptions
      return @each(->
        $(this).find('legend').not('fieldset fieldset fieldset legend,.collapsed,.collapsible').bind('click.collapse', (e) ->
          $(this).trigger 'collapsebeforeclick', $(this).parent('.collapsible')
          if $(this).parent().hasClass('collapsed')
            $(this).parent().removeClass('collapsed').addClass 'collapsible'
          $(this).removeClass 'collapsed'
          $(this).parent().children().not('legend').not('[type="radio"]').slideToggle options.animation, ->
            if $(this).is(':visible')
              $(this).parent().find('legend').addClass 'collapsible'
            else
              $(this).parent().addClass('collapsed').children('legend').addClass 'collapsed'
            return
          $(this).trigger 'collapseafterclick', $(this).parent('.collapsible')
          return
        ).addClass('collapsible').parent().addClass 'collapsible'
        switch options.start
          when 'close'
            $(this).find('legend').click()
          when 'first'
            $(this).find('legend').each (index) ->
              if index > 0
                $(this).click()
              return
        $(this).on 'collapsecreate', options.create
        $(this).on 'collapsebeforeclick', options.beforeClick
        $(this).on 'collapseafterclick', options.afterClick
        $(this).trigger 'collapsecreate', $(this)
        return
      )
    return
  return
) jQuery

